included:
  - Sources
  - Tests
excluded:
  - .build
disabled_rules:
  - force_try
  - force_unwrapping
  - identifier_name
  - unused_optional_binding
  - vertical_parameter_alignment_on_call # False positive with Multiple trailing closures
  # TODO: enable in future
  - function_body_length
  - type_body_length
file_length:
  ignore_comment_only_lines: true
line_length:
  warning: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
type_name:
  allowed_symbols:
    - _
  excluded:
    - OR
    - or
large_tuple:
  warning: 3
  error: 4
cyclomatic_complexity:
  ignores_case_statements: true
# trailing_closure:
#   only_single_muted_parameter: true
trailing_comma:
  mandatory_comma: true
todo:
  only: FIXME
