name: Release
on:
  push:
    tags: '*'
jobs:
  podspec:
    runs-on: macOS-latest
    env:
      POD_VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Lint
      run: pod spec lint
    - name: Deploy podspec
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: pod trunk push StubNetworkKit.podspec
